"""ragleakguard CLI — point it at a vector store and scan for exposed sensitive data."""
import os
from typing import Optional

import typer
from rich import print

from ragleakguard.detect import (
    DetectionError,
    DetectionRuntimeError,
    MalformedLocaleError,
    MissingDetectionDependencyError,
    MissingDetectionModelError,
    UnsupportedLocaleError,
    normalize_locale,
    validate_detection_runtime,
)


EXIT_SCAN_FAILURE = 1
EXIT_USAGE = 2
EXIT_DETECTION_RUNTIME = 3
EXIT_MONITOR_STATE = 4
EXIT_WEBHOOK = 5
EXIT_CONNECTOR_UNAVAILABLE = 6

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help=(
        "Bounded operator-snapshot Chroma scanning is available; direct/live "
        "source-store scanning remains disabled."
    ),
)


@app.callback()
def main():
    """RAGLeakGuard safety boundary and local credential helpers."""


def _abort_detection(error: DetectionError) -> None:
    """Print a static, privacy-safe failure and exit with the documented code."""
    if isinstance(error, MalformedLocaleError):
        print("[red]Invalid locale.[/] Use a two-letter code such as 'au'.")
        raise typer.Exit(EXIT_USAGE)
    if isinstance(error, UnsupportedLocaleError):
        print("[red]Unsupported locale.[/] Available locale packs: au.")
        raise typer.Exit(EXIT_USAGE)
    if isinstance(error, MissingDetectionDependencyError):
        print("[red]Detection unavailable.[/] Install the optional detection dependencies.")
        raise typer.Exit(EXIT_DETECTION_RUNTIME)
    if isinstance(error, MissingDetectionModelError):
        print("[red]Detection unavailable.[/] Install the required spaCy model 'en_core_web_sm'.")
        raise typer.Exit(EXIT_DETECTION_RUNTIME)
    if isinstance(error, DetectionRuntimeError):
        print("[red]Detection unavailable.[/] The detection runtime could not be initialized.")
        raise typer.Exit(EXIT_DETECTION_RUNTIME)
    print("[red]Detection configuration is invalid.[/]")
    raise typer.Exit(EXIT_USAGE)


def _validated_locale(locale: Optional[str]) -> Optional[str]:
    try:
        return validate_detection_runtime(locale)
    except DetectionError as error:
        _abort_detection(error)


def _validated_locale_syntax(locale: Optional[str]) -> Optional[str]:
    """Preserve locale usage validation without initializing detection."""
    try:
        return normalize_locale(locale)
    except DetectionError as error:
        _abort_detection(error)


def _abort_chroma_unavailable() -> None:
    """Emit the exact static disabled-path message and fail closed."""
    from ragleakguard.connectors import CHROMA_DISABLED_MESSAGE

    typer.echo(CHROMA_DISABLED_MESSAGE)
    raise typer.Exit(EXIT_CONNECTOR_UNAVAILABLE)


def _abort_monitor(error) -> None:
    """Emit static monitor/key remediation; never interpolate exceptions."""
    from ragleakguard import monitor as mon

    if isinstance(error, mon.LegacyMonitorStateError):
        print(
            "[red]Version-1 monitor state is incompatible and was preserved.[/] "
            "Preserve the legacy file, choose a new --state path, and explicitly "
            "initialize a version-3 baseline with --initialize."
        )
    elif isinstance(error, mon.MonitorBaselineRequiredError):
        print(
            "[red]Monitor baseline is absent.[/] Confirm the checkpoint was not lost "
            "or deleted, then explicitly create a version-3 baseline with --initialize."
        )
    elif isinstance(error, mon.MonitorInitializationError):
        print(
            "[red]Monitor initialization refused.[/] An existing state path is never "
            "overwritten; preserve it or choose a new --state path."
        )
    elif isinstance(error, mon.MonitorKeyMismatchError):
        print(
            "[red]Monitor key, construction, or store scope does not match state.[/] "
            "The checkpoint was preserved. Restore the original key and arguments, "
            "or explicitly initialize a new state path."
        )
    elif isinstance(error, mon.MonitorKeyError):
        print(
            "[red]Monitor key is unavailable or invalid.[/] Provide a compatible "
            "monitor-purpose key file generated by 'ragleakguard generate-monitor-key'."
        )
    elif isinstance(error, mon.MonitorStateError):
        print(
            "[red]Monitor state is invalid or unauthenticated.[/] The checkpoint was "
            "preserved. Restore a known-good backup or explicitly initialize a new path."
        )
    else:
        print(
            "[red]Monitor checkpoint failed.[/] No checkpoint was replaced; "
            "no success or alert was emitted."
        )
    raise typer.Exit(EXIT_MONITOR_STATE)


def _abort_webhook_preflight() -> None:
    print(
        "[red]Webhook configuration failed.[/] Provide a valid HTTPS URL and a "
        "dedicated secret file generated by 'ragleakguard generate-webhook-secret'."
    )
    raise typer.Exit(EXIT_WEBHOOK)


def _abort_webhook_preparation() -> None:
    print(
        "[red]Webhook alert preparation failed.[/] The prior checkpoint was "
        "preserved and no request was sent."
    )
    raise typer.Exit(EXIT_WEBHOOK)


def _abort_pending_configuration() -> None:
    print(
        "[red]A webhook alert is pending.[/] Provide the configured protocol-v2 "
        "HTTPS receiver and protocol-v2 secret; the source was not accessed."
    )
    raise typer.Exit(EXIT_WEBHOOK)


def _abort_pending_backoff() -> None:
    print(
        "[red]A webhook alert is pending.[/] Retry backoff has not elapsed; "
        "the source was not accessed and no request was sent."
    )
    raise typer.Exit(EXIT_WEBHOOK)


def _abort_pending_retry() -> None:
    print(
        "[red]Webhook retry cannot proceed safely.[/] The authenticated pending "
        "alert was preserved; the source was not accessed and no request was sent."
    )
    raise typer.Exit(EXIT_WEBHOOK)


def _abort_retry_checkpoint() -> None:
    print(
        "[red]Webhook retry checkpoint failed.[/] The last authenticated pending "
        "alert was preserved; delivery may be ambiguous."
    )
    raise typer.Exit(EXIT_MONITOR_STATE)


def _abort_pending_clear() -> None:
    print(
        "[red]Webhook delivery is ambiguous.[/] A 2xx response was accepted but "
        "the pending alert could not be durably cleared; a retry may duplicate it."
    )
    raise typer.Exit(EXIT_MONITOR_STATE)


@app.command("generate-monitor-key")
def generate_monitor_key(
    output: str = typer.Option(..., "--output", help="New local monitor key file"),
):
    """Generate a new 256-bit monitor-purpose key without overwriting a path."""
    from ragleakguard import monitor as mon

    try:
        mon.generate_key_file(output)
    except mon.MonitorError:
        print(
            "[red]Monitor key generation failed.[/] No existing key was overwritten."
        )
        raise typer.Exit(EXIT_MONITOR_STATE)
    print(
        "[green]Monitor key generated.[/] Restrict access, back it up securely, "
        "and provide it to monitor with --key-file."
    )
    raise typer.Exit(0)


@app.command("generate-webhook-secret")
def generate_webhook_secret(
    output: str = typer.Option(..., "--output", help="New webhook signing secret file"),
):
    """Generate a dedicated 256-bit webhook secret without overwriting a path."""
    from ragleakguard import monitor as mon

    try:
        mon.generate_webhook_secret_file(output)
    except mon.WebhookError:
        print(
            "[red]Webhook signing secret generation failed.[/] "
            "No existing file was overwritten."
        )
        raise typer.Exit(EXIT_WEBHOOK)
    print(
        "[green]Webhook signing secret generated.[/] Restrict access, back it up "
        "securely, and provision it separately to the verifying receiver."
    )
    raise typer.Exit(0)


@app.command()
def scan(
    source: str = typer.Option(
        ..., "--source", help="Source type: chroma (operator snapshots only)"
    ),
    path: Optional[str] = typer.Option(
        None,
        "--path",
        help="Rejected legacy direct/live store path",
    ),
    snapshot: Optional[str] = typer.Option(
        None,
        "--snapshot",
        help="Offline, complete, operator-created Chroma snapshot directory",
    ),
    work_parent: Optional[str] = typer.Option(
        None,
        "--work-parent",
        help="Existing private directory for the disposable validated copy",
    ),
    source_id: Optional[str] = typer.Option(
        None,
        "--source-id",
        help="Pseudonymous ASCII source identifier for aggregate reporting",
    ),
    acknowledge_offline_complete_snapshot: bool = typer.Option(
        False,
        "--acknowledge-offline-complete-snapshot",
        help="Confirm the supplied directory is an offline, complete snapshot",
    ),
    report: str = typer.Option(
        "report.md", "--report", help="Atomically finalized aggregate Markdown report"
    ),
    locale: str = typer.Option(
        None,
        "--locale",
        help="Locale pack: au (case-insensitive; surrounding whitespace ignored)",
    ),
):
    """Detect sensitive-data types in one bounded operator snapshot.

    Direct/live Chroma access and legacy --path requests remain disabled.

    Exit codes: 0 = aggregate report durably finalized; 1 = scan/report failure;
    2 = usage/locale error; 3 = detection runtime unavailable; 6 = candidate
    dependency or activation environment unavailable.
    """
    source = source.lower()
    if source != "chroma":
        print(f"[red]Source '{source}' isn't supported.[/] No source connector is available.")
        raise typer.Exit(EXIT_USAGE)
    if path is not None:
        print(
            "[red]Legacy --path is rejected.[/] Direct/live Chroma access remains "
            "disabled; supply an operator-created snapshot."
        )
        raise typer.Exit(EXIT_USAGE)
    if snapshot is None or work_parent is None or source_id is None:
        print(
            "[red]Snapshot scan arguments are incomplete.[/] Provide --snapshot, "
            "--work-parent, and --source-id."
        )
        raise typer.Exit(EXIT_USAGE)
    if not acknowledge_offline_complete_snapshot:
        print(
            "[red]Snapshot acknowledgement is required.[/] Confirm an offline, "
            "complete operator-created snapshot."
        )
        raise typer.Exit(EXIT_USAGE)

    from ragleakguard import connectors
    from ragleakguard import report as reporting

    try:
        result = connectors.scan_chroma_snapshot(
            snapshot,
            work_parent,
            source_id=source_id,
            acknowledge_offline_complete_snapshot=True,
            locale=locale,
        )
    except DetectionError as error:
        _abort_detection(error)
    except connectors.InvalidChromaSnapshotRequest:
        print("[red]Snapshot scan request is invalid.[/]")
        raise typer.Exit(EXIT_USAGE)
    except connectors.ChromaSnapshotUnavailableError:
        print(
            "[red]Snapshot-backed Chroma scanning is unavailable in this environment.[/]"
        )
        raise typer.Exit(EXIT_CONNECTOR_UNAVAILABLE)
    except connectors.ChromaSnapshotScanError:
        print(
            "[red]Snapshot-backed Chroma scan failed closed.[/] No report was replaced."
        )
        raise typer.Exit(EXIT_SCAN_FAILURE)

    try:
        aggregate_report = reporting.build_report(
            dict(result.detector.finding_counts_by_type),
            result.records_completed,
            result.detector.records_with_findings,
            source="chroma-snapshot",
            path=source_id,
        )
        reporting._finalize_report(aggregate_report, report)
    except BaseException:
        print(
            "[red]Aggregate report finalization failed.[/] No success was reported."
        )
        raise typer.Exit(EXIT_SCAN_FAILURE)
    print(
        "[green]Snapshot-backed Chroma scan completed; aggregate report finalized.[/]"
    )
    raise typer.Exit(0)


def _deliver_pending_alert(
    mon,
    *,
    state: str,
    records,
    crypto,
    scope_token: str,
    pending_alert,
    webhook_target,
    webhook_secret,
) -> None:
    """Make at most one attempt and durably retain or clear the outbox entry."""
    try:
        due = mon.pending_alert_is_due(pending_alert)
    except mon.WebhookRetryError:
        _abort_pending_retry()
    if not due:
        _abort_pending_backoff()

    try:
        prepared = mon.prepare_webhook_request(
            True,
            webhook_target,
            webhook_secret,
            pending_alert["delivery_id"],
        )
    except mon.WebhookError:
        _abort_webhook_preparation()

    try:
        mon.post_webhook(prepared)
    except mon.WebhookError:
        try:
            updated = mon.advance_pending_alert(pending_alert)
            mon.save_state(
                state,
                records,
                crypto,
                scope_token,
                pending_alert=updated,
            )
        except (mon.MonitorError, mon.WebhookError):
            _abort_retry_checkpoint()
        print(
            "[red]Webhook delivery failed.[/] The authenticated pending alert "
            "was retained for a bounded retry."
        )
        raise typer.Exit(EXIT_WEBHOOK)

    try:
        mon.save_state(
            state,
            records,
            crypto,
            scope_token,
            pending_alert=None,
        )
    except mon.MonitorError:
        _abort_pending_clear()
    print(
        "[green]Webhook response accepted; pending alert cleared.[/] "
        "No downstream processing is claimed."
    )


@app.command()
def monitor(
    source: str = typer.Option(
        ..., "--source", help="Source type: chroma (new scans are disabled)"
    ),
    path: str = typer.Option(
        None,
        "--path",
        help="Exact store-scope value for state authentication; source is not accessed",
    ),
    locale: str = typer.Option(
        None,
        "--locale",
        help="Locale pack: au (case-insensitive; surrounding whitespace ignored)",
    ),
    state: str = typer.Option(
        ".rlg-state.json",
        "--state",
        help="Authenticated version-3 checkpoint and one-entry outbox",
    ),
    webhook: Optional[str] = typer.Option(
        None,
        "--webhook",
        help="HTTPS receiver for one authenticated exposure-change alert",
    ),
    webhook_secret_file: Optional[str] = typer.Option(
        None,
        "--webhook-secret-file",
        help="Dedicated protocol-v2 webhook secret; required with --webhook",
    ),
    key_file: str = typer.Option(
        ...,
        "--key-file",
        help="Explicit monitor-purpose key file",
    ),
    initialize: bool = typer.Option(
        False,
        "--initialize",
        help="Authorize baseline path validation; creation is disabled with new scans",
    ),
    once: bool = typer.Option(
        True,
        "--once",
        help="Run one pending delivery attempt or reach the disabled new-scan boundary",
    ),
):
    """Recover an existing pending alert; fail closed before every new scan.

    Every run requires --key-file. New scans are disabled; new baselines are unavailable.

    Exit codes: 0 = pending alert accepted and cleared; 2 = usage/locale error;
    4 = monitor key/state failure; 5 = webhook pending/configuration/preparation/
    delivery failure; 6 = direct Chroma scanning disabled.
    """
    source = source.lower()
    if source == "chroma":
        if not path:
            print("[red]--path is required for chroma (the store directory).[/]")
            raise typer.Exit(EXIT_USAGE)
        _validated_locale_syntax(locale)
    else:
        print(f"[red]Source '{source}' isn't supported.[/] No source connector is available.")
        raise typer.Exit(EXIT_USAGE)

    from ragleakguard import monitor as mon

    webhook_target = None
    webhook_secret = None
    webhook_supplied = webhook is not None
    webhook_secret_supplied = webhook_secret_file is not None
    if webhook_secret_supplied and not webhook_supplied:
        print(
            "[red]Webhook configuration is invalid.[/] "
            "--webhook-secret-file requires --webhook."
        )
        raise typer.Exit(EXIT_USAGE)
    if webhook_supplied and not webhook_secret_supplied:
        _abort_webhook_preflight()
    if webhook_supplied:
        try:
            webhook_target = mon.validate_webhook_url(webhook)
            webhook_secret = mon.load_webhook_secret_file(webhook_secret_file)
        except mon.WebhookError:
            _abort_webhook_preflight()

    try:
        key = mon.load_key_file(key_file)
        crypto = mon.MonitorCrypto(key)
        scope_token = crypto.scope_token(source, path)
        if initialize and os.path.lexists(state):
            raise mon.MonitorInitializationError("Monitor state already exists.")
        previous = mon.load_state(state, crypto, scope_token)
        if previous is None and not initialize:
            raise mon.MonitorBaselineRequiredError(
                "Explicit monitor initialization is required."
            )
    except mon.MonitorError as error:
        _abort_monitor(error)

    pending_alert = None
    if previous is not None and previous.get("version") == mon.STATE_VERSION:
        pending_alert = previous["pending_alert"]
    if pending_alert is not None:
        if webhook_target is None or webhook_secret is None:
            _abort_pending_configuration()
        _deliver_pending_alert(
            mon,
            state=state,
            records=previous["records"],
            crypto=crypto,
            scope_token=scope_token,
            pending_alert=pending_alert,
            webhook_target=webhook_target,
            webhook_secret=webhook_secret,
        )
        raise typer.Exit(0)

    _abort_chroma_unavailable()


if __name__ == "__main__":
    app()
