"""ragleakguard CLI — point it at a vector store and scan for exposed sensitive data."""
import os
from typing import Optional

import typer
from rich import print

from ragleakguard.detect import (
    DetectionError,
    DetectionRuntimeError,
    MalformedLocaleError,
    MissingDetectionDependencyError,
    MissingDetectionModelError,
    UnsupportedLocaleError,
    validate_detection_runtime,
)


EXIT_USAGE = 2
EXIT_DETECTION_RUNTIME = 3
EXIT_MONITOR_STATE = 4
EXIT_WEBHOOK = 5

app = typer.Typer(add_completion=False, no_args_is_help=True, help="Scan your AI's vector database for exposed sensitive data.")


@app.callback()
def main():
    """ragleakguard — find sensitive data exposed in your AI's vector store."""


def _abort_detection(error: DetectionError) -> None:
    """Print a static, privacy-safe failure and exit with the documented code."""
    if isinstance(error, MalformedLocaleError):
        print("[red]Invalid locale.[/] Use a two-letter code such as 'au'.")
        raise typer.Exit(EXIT_USAGE)
    if isinstance(error, UnsupportedLocaleError):
        print("[red]Unsupported locale.[/] Available locale packs: au.")
        raise typer.Exit(EXIT_USAGE)
    if isinstance(error, MissingDetectionDependencyError):
        print("[red]Detection unavailable.[/] Install the optional detection dependencies.")
        raise typer.Exit(EXIT_DETECTION_RUNTIME)
    if isinstance(error, MissingDetectionModelError):
        print("[red]Detection unavailable.[/] Install the required spaCy model 'en_core_web_sm'.")
        raise typer.Exit(EXIT_DETECTION_RUNTIME)
    if isinstance(error, DetectionRuntimeError):
        print("[red]Detection unavailable.[/] The detection runtime could not be initialized.")
        raise typer.Exit(EXIT_DETECTION_RUNTIME)
    print("[red]Detection configuration is invalid.[/]")
    raise typer.Exit(EXIT_USAGE)


def _validated_locale(locale: Optional[str]) -> Optional[str]:
    try:
        return validate_detection_runtime(locale)
    except DetectionError as error:
        _abort_detection(error)


def _abort_monitor(error) -> None:
    """Emit static monitor/key remediation; never interpolate exceptions."""
    from ragleakguard import monitor as mon

    if isinstance(error, mon.LegacyMonitorStateError):
        print(
            "[red]Version-1 monitor state is incompatible and was preserved.[/] "
            "Preserve the legacy file, choose a new --state path, and explicitly "
            "initialize a version-2 baseline with --initialize."
        )
    elif isinstance(error, mon.MonitorBaselineRequiredError):
        print(
            "[red]Monitor baseline is absent.[/] Confirm the checkpoint was not lost "
            "or deleted, then explicitly create a version-2 baseline with --initialize."
        )
    elif isinstance(error, mon.MonitorInitializationError):
        print(
            "[red]Monitor initialization refused.[/] An existing state path is never "
            "overwritten; preserve it or choose a new --state path."
        )
    elif isinstance(error, mon.MonitorKeyMismatchError):
        print(
            "[red]Monitor key, construction, or store scope does not match state.[/] "
            "The checkpoint was preserved. Restore the original key and arguments, "
            "or explicitly initialize a new state path."
        )
    elif isinstance(error, mon.MonitorKeyError):
        print(
            "[red]Monitor key is unavailable or invalid.[/] Provide a compatible "
            "monitor-purpose key file generated by 'ragleakguard generate-monitor-key'."
        )
    elif isinstance(error, mon.MonitorStateError):
        print(
            "[red]Monitor state is invalid or unauthenticated.[/] The checkpoint was "
            "preserved. Restore a known-good backup or explicitly initialize a new path."
        )
    else:
        print(
            "[red]Monitor checkpoint failed.[/] No checkpoint was replaced; "
            "no success or alert was emitted."
        )
    raise typer.Exit(EXIT_MONITOR_STATE)


def _abort_webhook_preflight() -> None:
    print(
        "[red]Webhook configuration failed.[/] Provide a valid HTTPS URL and a "
        "dedicated secret file generated by 'ragleakguard generate-webhook-secret'."
    )
    raise typer.Exit(EXIT_WEBHOOK)


def _abort_webhook_preparation() -> None:
    print(
        "[red]Webhook alert preparation failed.[/] The prior checkpoint was "
        "preserved and no request was sent."
    )
    raise typer.Exit(EXIT_WEBHOOK)


@app.command("generate-monitor-key")
def generate_monitor_key(
    output: str = typer.Option(..., "--output", help="New local monitor key file"),
):
    """Generate a new 256-bit monitor-purpose key without overwriting a path."""
    from ragleakguard import monitor as mon

    try:
        mon.generate_key_file(output)
    except mon.MonitorError:
        print(
            "[red]Monitor key generation failed.[/] No existing key was overwritten."
        )
        raise typer.Exit(EXIT_MONITOR_STATE)
    print(
        "[green]Monitor key generated.[/] Restrict access, back it up securely, "
        "and provide it to monitor with --key-file."
    )
    raise typer.Exit(0)


@app.command("generate-webhook-secret")
def generate_webhook_secret(
    output: str = typer.Option(..., "--output", help="New webhook signing secret file"),
):
    """Generate a dedicated 256-bit webhook secret without overwriting a path."""
    from ragleakguard import monitor as mon

    try:
        mon.generate_webhook_secret_file(output)
    except mon.WebhookError:
        print(
            "[red]Webhook signing secret generation failed.[/] "
            "No existing file was overwritten."
        )
        raise typer.Exit(EXIT_WEBHOOK)
    print(
        "[green]Webhook signing secret generated.[/] Restrict access, back it up "
        "securely, and provision it separately to the verifying receiver."
    )
    raise typer.Exit(0)


@app.command()
def scan(
    source: str = typer.Option(..., "--source", help="Vector store type: chroma | pinecone"),
    path: str = typer.Option(None, "--path", help="Path or connection string for the store"),
    report: str = typer.Option("report.md", "--report", help="Where to write the report"),
    locale: str = typer.Option(
        None,
        "--locale",
        help="Locale pack: au (case-insensitive; surrounding whitespace ignored)",
    ),
):
    """Scan a vector store and report exposed sensitive data.

    Pipeline (being built): connector -> extract text -> detect -> risk-score -> report.

    Exit codes: 0 = completed · 2 = usage/locale error · 3 = detection unavailable.
    """
    source = source.lower()
    if source == "chroma":
        from ragleakguard.connectors import read_chroma

        if not path:
            print("[red]--path is required for chroma (the store directory).[/]")
            raise typer.Exit(EXIT_USAGE)
        locale = _validated_locale(locale)
        items = list(read_chroma(path))
    else:
        print(f"[red]Source '{source}' isn't supported yet (try: chroma).[/]")
        raise typer.Exit(EXIT_USAGE)

    if not items:
        print(f"[bold]ragleakguard[/] read [bold green]0[/] item(s) from [bold]{source}[/] at '{path}'.")
        raise typer.Exit(0)

    from collections import Counter

    by_type: Counter = Counter()
    total = flagged = 0
    try:
        from ragleakguard.detect import detect

        for it in items:
            found = detect(it["text"], locale=locale)
            if found:
                flagged += 1
            total += len(found)
            by_type.update(f["type"] for f in found)
    except DetectionError as error:
        _abort_detection(error)

    print(f"[bold]ragleakguard[/] read [bold green]{len(items)}[/] item(s) from [bold]{source}[/] at '{path}'.")
    print(f"\n[bold red]⚠  {total}[/] sensitive finding(s) across [bold]{flagged}/{len(items)}[/] records:")
    for entity, count in by_type.most_common():
        print(f"   [yellow]{entity:<16}[/] {count}")

    from ragleakguard.report import build_report

    md = build_report(dict(by_type), len(items), flagged, source=source, path=path)
    with open(report, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"\n[green]✓[/] Risk-scored report written to [bold]{report}[/].")
    raise typer.Exit(0)


@app.command()
def monitor(
    source: str = typer.Option(..., "--source", help="Vector store type: chroma | pinecone"),
    path: str = typer.Option(None, "--path", help="Path or connection string for the store"),
    locale: str = typer.Option(
        None,
        "--locale",
        help="Locale pack: au (case-insensitive; surrounding whitespace ignored)",
    ),
    state: str = typer.Option(
        ".rlg-state.json",
        "--state",
        help="Authenticated version-2 checkpoint (never raw data)",
    ),
    webhook: Optional[str] = typer.Option(
        None,
        "--webhook",
        help="HTTPS receiver for one authenticated exposure-change alert",
    ),
    webhook_secret_file: Optional[str] = typer.Option(
        None,
        "--webhook-secret-file",
        help="Dedicated webhook signing secret; required with --webhook",
    ),
    key_file: str = typer.Option(
        ...,
        "--key-file",
        help="Explicit monitor-purpose key file",
    ),
    initialize: bool = typer.Option(
        False,
        "--initialize",
        help="Explicitly create a new baseline; never overwrites existing state",
    ),
    once: bool = typer.Option(True, "--once", help="Run a single check (cron-friendly; the only mode in v1)"),
):
    """Re-scan a store and alert on NEW or CHANGED sensitive findings since the last run.

    New baselines require --initialize. Every run requires --key-file.

    Exit codes: 0 = initialized/no new exposure; 1 = new/changed findings;
    2 = usage/locale error; 3 = detection unavailable; 4 = monitor key/state failure;
    5 = webhook failure.
    """
    source = source.lower()
    if source == "chroma":
        from ragleakguard.connectors import read_chroma

        if not path:
            print("[red]--path is required for chroma (the store directory).[/]")
            raise typer.Exit(EXIT_USAGE)
        locale = _validated_locale(locale)
    else:
        print(f"[red]Source '{source}' isn't supported yet (try: chroma).[/]")
        raise typer.Exit(EXIT_USAGE)

    from ragleakguard import monitor as mon

    webhook_target = None
    webhook_secret = None
    webhook_supplied = webhook is not None
    webhook_secret_supplied = webhook_secret_file is not None
    if webhook_secret_supplied and not webhook_supplied:
        print(
            "[red]Webhook configuration is invalid.[/] "
            "--webhook-secret-file requires --webhook."
        )
        raise typer.Exit(EXIT_USAGE)
    if webhook_supplied and not webhook_secret_supplied:
        _abort_webhook_preflight()
    if webhook_supplied:
        try:
            webhook_target = mon.validate_webhook_url(webhook)
            webhook_secret = mon.load_webhook_secret_file(webhook_secret_file)
        except mon.WebhookError:
            _abort_webhook_preflight()

    try:
        key = mon.load_key_file(key_file)
        crypto = mon.MonitorCrypto(key)
        scope_token = crypto.scope_token(source, path)
        if initialize and os.path.lexists(state):
            raise mon.MonitorInitializationError("Monitor state already exists.")
        previous = mon.load_state(state, crypto, scope_token)
        if previous is None and not initialize:
            raise mon.MonitorBaselineRequiredError(
                "Explicit monitor initialization is required."
            )
    except mon.MonitorError as error:
        _abort_monitor(error)

    items = list(read_chroma(path))

    from ragleakguard.detect import detect

    try:
        current = mon.build_snapshot(
            items,
            detect,
            crypto,
            scope_token,
            locale=locale,
        )
    except DetectionError as error:
        _abort_detection(error)
    except mon.MonitorError as error:
        _abort_monitor(error)

    if previous is None:
        try:
            mon.save_state(
                state,
                current,
                crypto,
                scope_token,
                initialize=True,
            )
        except mon.MonitorError as error:
            _abort_monitor(error)
        print("[bold]ragleakguard monitor[/] - baseline initialized.")
        raise typer.Exit(0)

    delta = mon.diff(previous["records"], current)
    n_new, n_chg = len(delta["new"]), len(delta["changed"])
    if n_new == 0 and n_chg == 0:
        try:
            mon.save_state(state, current, crypto, scope_token)
        except mon.MonitorError as error:
            _abort_monitor(error)
        print(
            "[green]OK[/] No new exposure."
        )
        raise typer.Exit(0)

    prepared_webhook = None
    if webhook_target is not None:
        try:
            prepared_webhook = mon.prepare_webhook_request(
                True,
                webhook_target,
                webhook_secret,
            )
        except mon.WebhookError:
            _abort_webhook_preparation()

    try:
        mon.save_state(state, current, crypto, scope_token)
    except mon.MonitorError as error:
        _abort_monitor(error)

    if prepared_webhook is not None:
        try:
            mon.post_webhook(prepared_webhook)
        except mon.WebhookError:
            print(
                "[red]Webhook delivery failed.[/] No delivery success is claimed; "
                "the checkpoint was advanced and this alert may be lost."
            )
            raise typer.Exit(EXIT_WEBHOOK)

    print("[bold red]Exposure change detected.[/]")
    if prepared_webhook is not None:
        print("[green]Webhook alert delivered.[/]")

    raise typer.Exit(1)


if __name__ == "__main__":
    app()
