"""Reporting — turn raw findings into a risk-scored, human-readable report.

Severity weighting + regulatory framing + remediation = the security judgment
that makes a scan trustworthy, rather than a noisy entity dump.
"""
from typing import Dict

SEVERITY = {
    "AU_MEDICARE": "HIGH", "AU_TFN": "HIGH", "CREDIT_CARD": "HIGH",
    "IBAN_CODE": "HIGH", "MEDICAL_LICENSE": "HIGH",
    "PERSON": "MEDIUM", "EMAIL_ADDRESS": "MEDIUM", "PHONE_NUMBER": "MEDIUM",
    "LOCATION": "MEDIUM", "AU_ABN": "MEDIUM",
    "DATE_TIME": "LOW", "IP_ADDRESS": "LOW",
}


def _risk_level(by_type: Dict[str, int], n_flagged: int, n_records: int) -> str:
    has_high = any(SEVERITY.get(t) == "HIGH" for t in by_type)
    frac = (n_flagged / n_records) if n_records else 0.0
    if has_high and frac >= 0.25:
        return "HIGH"
    if has_high or frac >= 0.50:
        return "ELEVATED"
    return "MODERATE" if by_type else "LOW"


def build_report(by_type: Dict[str, int], n_records: int, n_flagged: int,
                 source: str = "chroma", path: str = "") -> str:
    """Build a Markdown risk report from aggregated findings."""
    total = sum(by_type.values())
    pct = f"{(n_flagged / n_records * 100):.0f}%" if n_records else "0%"
    level = _risk_level(by_type, n_flagged, n_records)

    lines = [
        "# RAGLeakGuard — Sensitive Data Report",
        "",
        f"- **Source:** `{source}` {path}".rstrip(),
        f"- **Records scanned:** {n_records}",
        f"- **Records with sensitive data:** {n_flagged} ({pct})",
        f"- **Total findings:** {total}",
        f"- **Risk level:** **{level}**",
        "",
        "## Findings by type",
        "",
        "| Type | Count | Severity |",
        "|------|------:|----------|",
    ]
    for t, c in sorted(by_type.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"| {t} | {c} | {SEVERITY.get(t, 'REVIEW')} |")

    lines += [
        "",
        "## Why this matters",
        "- These values are **embedded** in a vector store — text can be partially "
        "**reconstructed** from the vectors (embedding inversion), so they are *not* anonymous.",
        "- They are **hard to delete**: removing them from the live index does not remove them "
        "from backups, replicas, caches, or any fine-tuned model.",
        "- Under Australia's Privacy Act (APP 11) and the GDPR, holding this without controls can "
        "create **notifiable-breach** and **right-to-erasure** exposure.",
        "",
        "## Recommended actions",
        "1. **Prevent:** redact / tokenise sensitive fields *before* embedding.",
        "2. **Remediate:** delete affected records and rebuild the index from a sanitised source.",
        "3. **Purge copies:** backups, replicas, caches, logs.",
        "4. **Prove:** keep an erasure record for compliance.",
        "",
        "---",
        "_Generated by **RAGLeakGuard** (Diagnose). Detection is best-effort — tune recognisers for "
        "your jurisdiction; absence of a finding is not proof of safety._",
    ]
    return "\n".join(lines)
